version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   
      MYSQL_DATABASE: url_short               
      MYSQL_USER: root                   
      MYSQL_PASSWORD: root         
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql